import "./index.scss";

import { ViewTransitions } from "next-view-transitions";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="snap-y snap-mandatory flex flex-col">
      <body className={`antialiased bg-black contents`}>
        <ViewTransitions>
          <Header />
          {children}
        </ViewTransitions>
      </body>
    </html>
  );
}
